### ISSUE TITLE
problems with lack of reproduction of old CNN results

### ISSUE THREAD

**Issue by timm** [timm/700timesfaster#10]
"Because we were not able to implement Xu'sCNN, we use the same datasets so that we can compare our results without introducing implementation bias. "

1. where you you justify this?
2. how can we justify comparing our runtimes with their's when we dont run their rig? do we have rationale for believing our times aren't faster cause eg our hardware is better?

**Comment by Suvodeep90** [comment]
Most of the Deep Learning methods or tools from papers in SE are not publicly available or they are too complicated to implement, the XU's CNN is also not publicly available. Along with that CNNs normally have multiple layers and thousands or weights and connections between layers, a vert small deviation from original network can results in huge difference in performance. So we have not implemented XU's CNN network, all his result data is publicly available along with the hardware configuration(2.5GHz,16GB ram on 64bit platform). Our hardware configuration is almost similar to his with 3.00GHz processor with 16GB ram, running on 64bit platform. And also we have implemented FU's DE_SVM in our machine configuration and runtime is quite similar.
So we are assuming our results are comparable.

can this be a justification?

**Comment by timm** [comment]
yes

**Comment by Suvodeep90** [comment]
Is threat to validity a good section to add this to?
