### ISSUE TITLE
contribution list not so impressive

### ISSUE THREAD

**Issue by timm** [timm/700timesfaster#17]
"In summary, the contributions of this paper include:

- Offer local models as a technique to make learners contextaware as well as significantly faster
- Potentially present a faster method of text data classificationthan deep learning.
- Access to the code base - to reproduce, improve or refuteour results "

not that impressive a list . try again. here's  a model that might inspire you

![screen shot 2017-12-19 at 4 55 16 pm](https://user-images.githubusercontent.com/29195/34180625-6c9fb27c-e4dd-11e7-9f70-bfc7ad094756.png)

**Comment by Suvodeep90** [comment]
I have updated the contribution list, Is this list good or should i change it in some other way?

**Comment by Suvodeep90** [comment]
Contribution list updated
