### ISSUE TITLE
figures should be white background. 

### ISSUE THREAD

**Issue by timm** [timm/700timesfaster#8]
suggest you use google sheets. change fond size on x,y axis to 15 point before screen snapping same and creating a png for each.

as to fig14,fig15,fig16, please see Paper_Sampling_vs_EA and the command \quart{36}{10}{44}{0}

needs this in premable (before \begin{document}

\usepackage{picture}
\newcommand{\quart}[4]{\begin{picture}(100,6)%1
{\color{black}\put(#3,3){\circle*{4}}\put(#1,3){\line(1,0){#2}}}\end{picture}}
\newcommand{\quartr}[4]{\begin{picture}(100,6)%1
{\color{black}\put(#3,3){\color{red}\circle*{6}}\put(#1,3){\line(1,0){#2}}}\end{picture}}

you can use this to make pretty quartile charts like

![screen shot 2017-12-19 at 3 57 29 pm](https://user-images.githubusercontent.com/29195/34178529-928b4008-e4d5-11e7-8558-c69260d7e96a.png)

**Comment by timm** [comment]
for details of usage, see pom3_quartile.tex in https://www.sharelatex.com/project/56ae90792071baf806d16309

**Comment by Suvodeep90** [comment]
Changed the figures to have white background. Still working on making the changes for the stat files output.

**Comment by Suvodeep90** [comment]
changed the test results from figure to table with the above code. But not sure if the chart is correct or not.
