### ISSUE TITLE
need a cooler section2

### ISSUE THREAD

**Issue by timm** [timm/700timesfaster#9]
benefits and costs of deep learning. something like the following but don't use this vertbatim (make the words your own).

beneifts-- go hunt the ltierature for examples with DL kicked ass on problems where, previously, other methods had stopped leading to greater improvements.

then point out that DL has received some recent attention in the SE literature where various authors had found the method useful. for this you can steal some of the content from of 2.3 https://www.sharelatex.com/project/587fea8b93554fb1518c4b79

then point out one curious feature of past work on DL in SE: while it has shown that DL is competent, it is rarely compared to any alternate method. Rare execptions to this rule include https://dl.acm.org/citation.cfm?id=3106256 and https://dl.acm.org/citation.cfm?doid=3106237.3106290 (and maybe you can find a few more). with a few notes on each

then say something like there exists some complex data which are inherently high dimensonal and can benefit from DL. however, to date, it is not clear in there are many SE data sets with that property. the only way to be sure is to try. Note that if there exists methods simpler than DL then that would simplift repearability and faster science in SE. For these reasons, we explore DL and its alternatives.

**Comment by Suvodeep90** [comment]
Updated section 2
